version: '3'

services:
  web_api:
    build: .
    environment: 
      - NODE_ENV=development
    ports: 
      - '3000:3000'
    volumes:
      - .:/home/node/app
      #prevent host node_modules from accidently getting mounted in container
      - notused:/home/node/app/node_modules
    command: "yarn run start"
    #stdin_open: true
    #tty: true

volumes:
  notused: