version: '3'

services:
  web_api:
    image: node
    environment: 
      - NODE_ENV=development
    ports: 
      - '3000:3000'
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    command: "yarn run start"